### ISSUE TITLE
Requirements for a valid GIG (and for a valid `gigl` encoding)

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#104]
I'm not sure we have written down the GIG validity requirements anywhere. Here's my suggestion:

## Definition

A gig is a multidigraph with nodes indexed from _0..n_ and edges providing links between those node IDs. What makes this a GIG in particular, rather than a general graph, is that the edges are annotated with one or more intervals consisting of a (childLeft, childRight, childChromosome, parentLeft, parentRight, parentChromosome) tuple and the nodes each have a single (floating point) `time` value, with higher values indicating older times.

For efficiency the _gigl_ library denormalises edges and intervals, combining them into a single *iedges* table, each row of which is like this:

|  |  |  |  |  |  |  |  | optional |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| `child_left`  | `child_right` | `parent_left`  | `parent_right` | `childID`  | `parentID` | `child_chrom`  | `parent_chrom` |  `edgeID` |

### Base Requirements for any GIG (with biological justification)

* All values in an iedge row are assumed to be integers. The first 8 columns are nonnegative integers.
* The `edgeID` can be set to  `-1`, which is the default if it is not specified. Among all the rows with a `-1` edge value, each separate combination of (`childID`, `parentID`) is treated as belonging to a separate single edge. Otherwise, two rows sharing a non-negative `edge` ID must have the same `parent` and `child` values. Note that we currently do not use the edge IDs, but they could be useful to indicate different transmission paths e.g. in "recombination diamonds". 
* We must have a finite but nonzero `abs(child_right - child_left) == abs(parent_right - parent_left)` (meaning that we can't magic up genetic material from nowhere)
* iedges for a given `childID`+`child_chrom` cannot have overlapping `(child_left, child_right)` intervals (meaning that a single base pair can only have one parent)
* the `parentID` node time must be strictly older than the `childID` node time (cannot have time-travel: this is what makes the GIG a directed acyclic graph). Note that this requires us to map the `childID` and `parentID` to a node in the node table.

### Efficiency requirements (needed by a _gigl_ GIG)

In the _gigl_ library, we enforce the following requirements, for efficiency:

* `child_left` < `child_right` (but we can have `parent_left` > `parent_right` to indicate an inversion)
* Iedge row ordering requirements (together these impose a canonical order on the iedges, so that they can always be sorted into a strict order)
  - Iedge rows with the same `childID` are adjacent in the table
  - Within a set of rows with the same child ID, rows are ordered first by chromosome ID (ascending), then by `child_left` (ascending)
  - Between sets of rows with a different child ID, rows are ordered first by child node time (descending) then by `childID` (ascending)

### Other

Once we implement mutations, there may be other requirements. Meanwhile, here is how I am currently thinking of coding up the requirements above as flags:

```python
# GIG DEFINITIONAL REQUIREMENTS

IEDGES_DATA_ARE_INTEGERS = 1 << 0  # noqa: F401

# Most important: valid finite nonzero intervals with parent span == child span
IEDGES_VALID_INTERVALS = 1 << 1  # noqa: F401

# Second most important: each chromosome position in a child has only one edge above it
IEDGES_FOR_CHILD_NONOVERLAPPING = 1 << 2  # noqa: F401

# Ensure the graph is acyclic (requires knowledge of the times in the nodes table)
# Also useful for guaranteeing that there are nodes with the parent and child IDs
IEDGES_PARENT_OLDER_THAN_CHILD = 1 << 3  # noqa: F401

# Iedges with the same edge_ID must have the same combination of parentID / childID
# (note the inverse may not be true: iedges with the same parentID / childID can have
# different edge_IDs)
IEDGES_SAME_PARENT_CHILD_FOR_EDGE = 1 << 4  # noqa: F401

# IEDGE EFFICIENCY REQUIREMENTS (e.g. to define a canonical iedge order)

# keep child_left < child_right (but inversions will have parent_left > parent_right)
IEDGES_CHILD_INTERVAL_POSITIVE = 1 << 5  # noqa: F401

# all iedges with the same child ID are adjacent in the table
IEDGES_FOR_CHILD_ADJACENT = 1 << 6  # noqa: F401

# within a set of iedges for the same child, iedges are ordered first
# by chromosome number
IEDGES_FOR_CHILD_PRIMARY_ORDER_CHR_ASC = 1 << 7  # noqa: F401

# within a set of iedges for the same child & chromosome, iedges are ordered by left
# position (if IEDGES_FOR_CHILD_NONOVERLAPPING and IEDGES_CHILD_INTERVAL_POSITIVE are
# set, then this means that iedges must also be ordered by right position)
IEDGES_FOR_CHILD_SECONDARY_ORDER_LEFT_ASC = 1 << 8  # noqa: F401

# the adjacent rows for a child are ordered in descending order of child node time
# (requires knowledge of the times in the nodes table)
IEDGES_PRIMARY_ORDER_CHILD_TIME_DESC = 1 << 9  # noqa: F401

# ties (child nodes at the same time) are broken by putting the lowest child ID first
# (note: probably not very important, but creates a canonical ordering; it also implies
# IEDGES_FOR_CHILD_ADJACENT must be set)
IEDGES_SECONDARY_ORDER_CHILD_ID_ASC = 1 << 10  # noqa: F401

# These are the requierments that require us to know the node times
IEDGES_NODE_TIME_REQUIREMENTS = IEDGES_PARENT_OLDER_THAN_CHILD | IEDGES_PRIMARY_ORDER_CHILD_TIME_DESC

VALID_GIG = (
    IEDGES_DATA_ARE_INTEGERS | IEDGES_VALID_INTERVALS | IEDGES_FOR_CHILD_NONOVERLAPPING | IEDGES_PARENT_OLDER_THAN_CHILD | IEDGES_CHILD_INTERVAL_POSITIVE | IEDGES_FOR_CHILD_ADJACENT | IEDGES_FOR_CHILD_PRIMARY_ORDER_CHR_ASC | IEDGES_FOR_CHILD_SECONDARY_ORDER_LEFT_ASC | IEDGES_PRIMARY_ORDER_CHILD_TIME_DESC | IEDGES_SECONDARY_ORDER_CHILD_ID_ASC
)
```

**Comment by duncanMR** [comment]
That looks good to me! I think there might be additional ways in which the data structure could break in handcrafted examples, but they'd be more tricky to validate. You haven't added any checks for consistency between iedges going into a given node and iedges going out of that node. For example, `max(parent_right)` for iedges going out can't be greater than `max(child_right)` for iedges going in, since otherwise you could have a chunk of genome without ancestry. I don't think it's possible to generate such a case with simulation though, so it's probably not worth worrying about.

**Comment by hyanwong** [comment]
Ah, yes. But I think we *do* allow chunks without ancestry in `tskit`, which represent "missing data". Perhaps we should allow that and document it?

**Comment by hyanwong** [comment]
We should add a test that randomly re-orders a set of iedges, then sorts them, to check that `tables.sort()` always results in the same order.

Ideally, this would be a cause where we have different chromosomes (see #103 to address first)

**Comment by hyanwong** [comment]
This is all now encoded in the ValidFlags, and also in the docstring for `tables.graph()`, so I'm closing
