### ISSUE TITLE
Storing length of the genome

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#27]
At several points we might need to look up the length of a genome. We can find if by looking at the rightmost position of all the edges leading into it (i.e. the largest `child_right` of the in-edges). But this might be tedious if we have to do it a lot. Is it worth caching this by also having a `span` attribute on the node?

If we do store this on the node, there is the potential for inconsistency between the in-edges and the stand, but I guess we can check that when turning the tables into a GIG.

**Comment by duncanMR** [comment]
Are you suggesting that we add a `span` column to the nodes table? I'm not sure what you mean by 'the stand'. I definitely think we should cache the node spans, but I think it should only be done internally when we turn the tables into a GIG. We will probably need to calculate all the node spans anyway when we validate the tables: for example, we could check that the spans calculated from the out-edges of a node are not greater than those calculated from the in-edges.

**Comment by hyanwong** [comment]
Sorry "the stand" was an auto-correct typo. I meant the span.

**Comment by hyanwong** [comment]
If we address https://github.com/hyanwong/GeneticInheritanceGraphLibrary/issues/94 then we can find the highest `child_right` for a node in constant time. As long as the graph has been sample-resolved, that should be fine for all nodes apart from root nodes.

If we want to also look at the rightmost location among edges where that node is a parent, it can only be done once we have the `iedge_map_sorted_by_parent` array (which is available in the GIG but not to the tables).

So I suggest that we have a tables function `max_child_position(n)`,  and when we create a gig, we also cache a `max_position` attribute (which is the maximum of the child and parent positions). We can dump the `max_position` in each `node` object returned by `gig.nodes()`
