### ISSUE TITLE
Encoding inversions, and integer positions

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#41]
I had a quick thought about inversions. I think it makes sense to keep the same notation of half-open intervals in a GIG as in a tree sequence. That is, the interval 0...4 is treated as [0, 4), such that 4 is not included in the interval.

This is all fine for duplications and deletions. For inversions, we need to decide whether a parent interval of 0...4 coupled with a child interval of 4...0 means either [0, 4) -> (4, 0] or (0, 4] -> [4, 0). Or to put it another way, is position 4 in the parent included in the transformation. I think it makes sense for the intervals to be always open at the higher end, so that in this case, the parent position of 4 is not included, neither is the child position of 4. If we denote a parent position N as pN, and a child position M as cM, the intervals p[0,4) -> c[4,0) would then map

p0 -> c3
p1 -> c2
p2 -> c1
p3 -> c0

This seems nice and neat (and symmetrical) as long as we have integer intervals. However, with floating point numbers, according to this scheme, p3.5 would have to map to the (nonsensical) c-0.5. We therefore cannot combine this notation with floating point positions, unless we ban numbers in [0,1) and (sequence_length-1, sequence_length]  from inversion transformations.

**Comment by hyanwong** [comment]
Easiest is just to require integer intervals and have done with it. We might find it difficult to simulate infinite-sites or infinite-breakpoints (presumably we would just increase the sequence length to a huge value, and decrease the mutation/recombination rate to compensate). But even with a floating-point representation, you get occasional clashes in e.g. mutation position with very large simulations, so we would have to cope with this anyway.

**Comment by duncanMR** [comment]
I agree that we need to commit to integer genome coordinates; it makes biological sense and it makes our lives easier. Your convention that parent interval should always be of the form [l, r) makes sense to me too, since we already have a convention that the parent interval is never reversed in the intervals table. So this would ensure that the parent interval will always work just like a tskit interval. 

I would like to construct examples with nested inversions, because that will test whether our interval conventions work in pathological cases.

**Comment by hyanwong** [comment]
In fact, if we say that the larger number is always closed, we could either say that the parent is 4...0 and the child is 0..4, or vice versa. I think that is independent of the convention that the parent interval is always represented by `low, high` intervals.

**Comment by hyanwong** [comment]
After coding the Hudson algorithm on a fixed GIG, I think that it is clearer if we require child_left < child_right.

There is another issue to do with transforming integer coordinates vs intervals. Say we have edges (as in #2) like:

`parent=12, child=8, parent_left=160, child_left=80, parent_right=80, child_right=160`
`parent=12, child=8, parent_left=160, child_left=160, parent_right=200, child_right=200`

Then the base at position 80 in the child should get transformed to position 159 in the parent (and 160 in the child will remain at 160 in the parent). However, let's say that instead of a single point, we wish to transform an *interval* (say that we are only tracing the interval [100, 160) in the child, because that's all that is required to be passed up.

if we wish to transform this *interval* (rather than a fixed position), we should transform it to (140, 80], so that the "number" `160)` in the child interval is transformed into `80]`. This is how I have coded it, but it seems a bit inelegant. I wonder if there is a more logical way?

```python
    def transform_to_parent(self, child_position, is_interval=False):
        """
        Transform a position from child coordinates to parent coordinates.
        If this is an inversion and we are transforming a point position,
        then an edge such as [0, 10) -> (10, 0] means that position 9 gets
        transformed to 0, and position 10 is not transformed at all. This
        means subtracting 1 from the returned (transformed) position.

        If, on the other hand, we are transforming an interval, then we
        don't want to subtract the one.
        """
        if child_position < self.child_left or child_position > self.child_right:
            raise ValueError(
                f"Position {child_position} is not in the child interval for {self}"
            )
        if self.is_inversion():
            if is_interval:
                return (self.child_right - child_position + self.child_left) + (
                    self.child_right - self.parent_left
                )
            else:
                return (self.child_right - child_position + self.child_left - 1) + (
                    self.child_right - self.parent_left
                )
        else:
            return child_position - self.child_left + self.parent_left
```

**Comment by hyanwong** [comment]
Yes, this sounds good to me, thanks.

**Comment by duncanMR** [comment]
> Yes, this sounds good to me, thanks. I assume you are fine with insisting that child_left < child_right for inversions?

Yup, that definitely seems to be the most convenient convention.

**Comment by duncanMR** [comment]
That might be helpful indeed, to make it clear when the unit of computation is a position versus an interval.

**Comment by hyanwong** [comment]
> > Yes, this sounds good to me, thanks. I assume you are fine with insisting that child_left < child_right for inversions?
> 
> Yup, that definitely seems to be the most convenient convention.

Great. I will check for that on validation, and set up classes accordingly.

**Comment by duncanMR** [comment]
That's a tough one. On second thought, I think the last option would be best for now, since it seems to be the simplest solution for the applications we have at the moment. I'm not keen on the 2nd option, since detecting types internally could easily lead to misleading behavour. I don't know how the interval class is used in tskit algorithms, but I'm inclined to delay creating one until we're sure it is a useful abstraction for multiple usecases.

**Comment by hyanwong** [comment]
Good points. The interval class (introduced by me!) is only really useful so that (a) you can do `interval.span` on any interval and (b) so you can do `if (intervalA == intervalB): ...`

**Comment by hyanwong** [comment]
This seems clearest to me

```
new_interval = iedge.transform_interval(arbitrary_interval, direction=ROOTWISE)
new_interval = iedge.transform_interval(arbitrary_interval, ROOTWISE)  # equivalent
```
