### ISSUE TITLE
Validate edges on add_row

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#69]
During forward simulations, we will want to run the `find_mrca_regions` routine on the continuously-updated GIG. This means either freezing the tables into a GIG each generation, or allowing the `find_mrca_regions` routine to run directly on a set of (unfrozen) tables.

I think the second idea is more efficient, but `find_mrca_regions` assumes the edges have a particular form (for instance, that the child_left < child_right, and that the parent ID has a larger time than the child ID). To ensure this is the case, we should probably validate the edges on input (or have a "validated" flag in the tables that is unset if data is input that is not validated).

**Comment by hyanwong** [comment]
What we have to guarantee for `find_mrca_regions` to work:

Edges:

- [ ] parent node time > child node time
- [ ] child_left < child_right
- [ ] child_right - child_left == abs(parent_right - parent_left)
- [ ] iedges_for_child is defined, allowing us to loop efficiently over all the edges for a given child (see #70)

**Comment by duncanMR** [comment]
That sounds like an efficient approach to me. Is the inefficiency of repeated sorting already too limiting to get meaningful results in a reasonable time?  My only concern is that implementing the flag system might make it trickier to debug and refactor the simulation code while we are still figuring out how it performs with SVs.

**Comment by hyanwong** [comment]
I don't think it should make the simulation code more complex, TBH. It should all be hidden from the simulator.

**Comment by hyanwong** [comment]
I chatted to Kevin Thornton about some of this. For efficiency it is probably worth allowing the user to *say* that the added information forms a valid GIG without actually doing the validation. It should be possible to run simulations with the validation step (for testing) then without that step if we need efficiency.
