### ISSUE TITLE
Order edges by child time (and ID)?

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#70]
Tskit orders edges by the time of the parent node (then by parent node ID). Jerome says

> It's either because that's the order we want for simplify or that's the natural order coming out of coalescent Sims, I can't remember

However, when writing the `gig.sample_resolve` and `gig.find_mrca_regions` functions (both of which will be called repeatedly in forward sims), we only ever iterate over the edges by *child* ID:

https://github.com/hyanwong/GeneticInheritanceGraphLibrary/blob/ac05dd3bc93527759978807f23e2dc0ab56b9708/GeneticInheritanceGraphLibrary/graph.py#L457

This is because we pop a node off the stack and follow the edges up from that node to fill out the various node parent values.

I am strongly inclined to deviate from tskit here, and order the edges by child node ID / time. This has the additional benefit that each child can only have one parent at one position, so the edges for a given child cannot overlap. This provides a natural order to the edges for a child, without having to take into account the right-hand coordinate. It also means that we can interpret a sequence of edges for a given child as a list of intervals stored in a [portion](https://pypi.org/project/portion/) object.

Have you any thoughts, @duncanMR ?

**Comment by duncanMR** [comment]
That makes sense to me: we will generally want to make algorithms traverse rootwards when possible, to avoid dealing with duplications, so basing our conventions on the child nodes is sensible. Besides, once we have finished building a GIG via simulation, we can always sort the edges by parent node time and cache the resulting order of edge indices if that is more efficient for a given algorithm.

**Comment by hyanwong** [comment]
Great. I agree and will make this change.
