### ISSUE TITLE
Make the mrca structure into a class

### ISSUE THREAD

**Issue by hyanwong** [hyanwong/GeneticInheritanceGraphLibrary#79]
This would help accessing elements (e.g. you could use `mrca[id][(l, r)].u` instead of `mrca[id][(l, r)][0]`, and could attach viz methods.

I think we want to leave this internal and undocumented, however, and subject to change at any time.

We could [subclass from `dict`](https://realpython.com/inherit-python-dict/) for the main class, and use a namedtuple for the `u, v` elements.

**Comment by hyanwong** [comment]
I've added the namedtuple.

**Comment by hyanwong** [comment]
Added the subclassing from dict.

@duncanMR: you could add your viz to the MRCAdict class?

**Comment by duncanMR** [comment]
Sure, I'm working on it now.

**Comment by hyanwong** [comment]
This is now a class
